stages:
  - test

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install uv
    - uv pip install -r pyproject.toml
  script:
    - pytest tests/ || pytest src/tests/ || pytest
